# Generated by Django 5.1.7 on 2025-03-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_customstudentevaluationresponse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomStudentEvaluationResponse',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_approve_evaluation', 'Can approve evaluation'), ('can_manage_evaluation', 'Can manage evaluation')]},
        ),
    ]
