# Generated by Django 5.1.7 on 2025-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0004_delete_customstudentevaluationresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
