# Generated by Django 5.1.7 on 2025-03-31 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': []},
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='user_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.room'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.subject'),
        ),
        migrations.AlterField(
            model_name='studentevaluationquestion',
            name='student_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.studentevaluation'),
        ),
        migrations.AlterField(
            model_name='studentevaluationquestion',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TEXT', 'Text Response'), ('RATING', 'Rating Scale')], max_length=15),
        ),
        migrations.AlterField(
            model_name='studentevaluationresponse',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.schedule'),
        ),
        migrations.AlterField(
            model_name='studentevaluationresponse',
            name='student_eval_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.studentevaluationquestion'),
        ),
        migrations.AlterField(
            model_name='studentevaluationresponse',
            name='student_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.studentevaluation'),
        ),
        migrations.AlterField(
            model_name='studentevaluationresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
