# Generated by Django 5.1.7 on 2025-04-02 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0008_studentevaluation_import_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyassignment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.schedule'),
        ),
        migrations.AlterField(
            model_name='facultyassignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
